"""empty message

Revision ID: 1171ba2d0c21
Revises: cc582b40f51b
Create Date: 2024-10-27 18:05:05.615425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1171ba2d0c21'
down_revision = 'cc582b40f51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp',
               existing_type=mysql.VARCHAR(length=225),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp',
               existing_type=mysql.VARCHAR(length=225),
               nullable=False)

    # ### end Alembic commands ###
