"""empty message

Revision ID: 426d08981921
Revises: 4d0c1296f054
Create Date: 2024-10-22 11:35:38.276920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '426d08981921'
down_revision = '4d0c1296f054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('btc_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('eth_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('freezed_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('freezed_balance',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('eth_balance',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('btc_balance',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    # ### end Alembic commands ###
