"""empty message

Revision ID: 4d0c1296f054
Revises: 
Create Date: 2024-10-22 11:03:06.998794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0c1296f054'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminreg',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=20), nullable=False),
    sa.Column('admin_pwd', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_username')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=False),
    sa.Column('lname', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('zipcode', sa.String(length=64), nullable=False),
    sa.Column('btc_balance', sa.Numeric(), nullable=False),
    sa.Column('eth_balance', sa.Numeric(), nullable=False),
    sa.Column('freezed_balance', sa.Numeric(), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('ssn', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('check',
    sa.Column('check_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_name', sa.String(length=64), nullable=False),
    sa.Column('check_amount', sa.Numeric(), nullable=False),
    sa.Column('check_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('check_id')
    )
    op.create_table('transaction',
    sa.Column('trans_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trans_name', sa.String(length=64), nullable=False),
    sa.Column('trans_amount', sa.Numeric(), nullable=False),
    sa.Column('trans_filename', sa.String(length=64), nullable=False),
    sa.Column('trans_plan', sa.String(length=64), nullable=False),
    sa.Column('trans_status', sa.String(length=64), nullable=False),
    sa.Column('trans_action', sa.String(length=64), nullable=False),
    sa.Column('trans_date', sa.DateTime(), nullable=True),
    sa.Column('trans_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trans_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('trans_id')
    )
    op.create_table('upload',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('upload_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upload_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    op.drop_table('transaction')
    op.drop_table('check')
    op.drop_table('user')
    op.drop_table('adminreg')
    # ### end Alembic commands ###
