"""empty message

Revision ID: 5d3837299a66
Revises: 426d08981921
Create Date: 2024-10-22 18:59:53.809741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3837299a66'
down_revision = '426d08981921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename_front', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('filename_back', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('filename_back')
        batch_op.drop_column('filename_front')

    # ### end Alembic commands ###
