"""empty message

Revision ID: 6abdd08d2705
Revises: 5d3837299a66
Create Date: 2024-10-25 17:58:24.424041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6abdd08d2705'
down_revision = '5d3837299a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('filename_front')
        batch_op.drop_column('filename_back')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename_back', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('filename_front', mysql.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
